services:
  db:
    build:
      context: ./db
    ports:
      - "27017:27017"

  webapp:
    build:
      context: ./app
    ports:
      - "80:3000"
    environment:
      - DB_HOST=mongodb://db:27017/posts
    


